### PR TITLE
Exchange-wide updates incl. drop py2.7 tests

### PR DESCRIPTION
**Pull request by cognifloyd**
- Test infra for py2.7 is broken. Drop it.
- bootstrap tests/setup_testing_env.sh
- drop unnecessary execute permissions

### CODE REVIEW

**Review by arm4b — CHANGES_REQUESTED** [review]
Good draft :+1: 

As noted before in the Discussion https://github.com/StackStorm/discussions/issues/40#issuecomment-770078067 dropping the Python2 Tests in StackStorm Exchange de-facto means deprecation of the Python 2 with the respective pack metadata consequences, eg. `python_versions`.

Besides of that, let's do it nicely this time. Can you work with @blag or @nmaludy so they push your changes directly to `master` to avoid new portion of unnecessary notifications?

**Comment by cognifloyd** [comment]
@armab are you saying you'd like us to remove `python_versions` from pack metadata when we drop the python 2.7 exchange tests? Or put a message somewhere saying it's deprecated?

**Comment by blag** [comment]
We should not (yet) change `python_version`. We could add a warning in the READMEs, but honestly, and this point I don't think that will be too helpful. Anybody who is still running Python 2 already knows the risks they are taking. Whatever warning we would add would just be a drop in the ocean.

It would be ideal to test both versions of Python while we support both, there is no rule that that has to be the case. And we are already being nice by not ripping out Python 2 code and Python 2 from `python_versions` already.

**Comment by arm4b** [comment]
Replied in https://github.com/StackStorm/discussions/issues/40#issuecomment-770252138

**Pull request closed without merging**
